name: bloc_getit_supabase_project_abdualaziz_abbas_abdulaziz
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  flutter_screenutil: ^5.9.3
  get_it: ^9.0.5
  go_router: ^16.3.0
  supabase_flutter: ^2.10.3
  bloc: ^9.1.0
  freezed: ^3.2.3
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.10.1
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true
  assets:
    - .env
